Blockchain/WhatIsBlockchain.md

Added new folder Blockchain and added WhatIsBlockchain.md file
#4

Added new folder Blockchain and added WhatIsBlockchain.md file

---

General/WhatIsData.md

Added contents for General/WhatIsData.md
#10

Added contents for General/WhatIsData.md

---

App/WhatIsAppDevelopment.md

Added a file on App Development

---

Web/HowToLearnCSS.md

This PR adds the `HowToLearnCSS.md` as described in #19. 
I decided to keep the explanations relatively short to make it easier to read, but open to any feedback on it!

Add CSS file with short explanations and resources for learning CSS

---

Web/WhatIsReact.md

I have done the assigned work.
Please look into the concern.
#14

I have added the react part under the web folder

---

General/WhatIsAccessibility.md

This PR adds a `WhatIsAccessibility.md` file to the `General` directory to give a short explanation of best practices in the world of accessibility. It also includes a list of resources at the bottom to continue learning about accessibility for front-end development.
This PR will complete issue #25

Add `WhatIsAccessibility.md` to `General` directory

---

General/WhatIsMultithreading.md

WhatisMultithreading(Hacktoberfest-goodfirstissue)

---

Web/HowToLearnJS.md

Closes #20
(Create a file at path Web/HowToLearnJS.md)
I have added the HowToLearnJS.md file to provide a comprehensive and organized guide for learning JavaScript.
1. **Structure:** I have structured the content like the other files in the folder.
2. **Sections:** New sections have been added to cover topics such as asynchronous programming, ES6 features, front-end frameworks, server-side JavaScript with Node.js, and more.
3. **Descriptions:** Each key concept has been written with descriptions, making it easier for learners to grasp the basics.
4. **Resource List:** I've included a list of resources for learning JavaScript, ranging from official documentation to tutorials and online courses. This provides learners with a variety of options to choose from.
These changes aim to improve …

added HowToLearnJS.md file

---

General/OperatingSystem.md

OperatingSystem(Hacktoberfest)

---

General/ComputerNetworks.md

I kindly request your formal review of the content contained within this file, with reference to issue #33 .
Thank You😊

#33 Added a file on ComputerNetworks.md

---

ProgrammingLanguages/java/HowToLearnJava.md

I have added the how to learn java file with some resources.
please notify me if any changes are required.
closes #38

Added How to learn java file

---

Coding/Algorithms/Introduction.md

content added in coding/algorithm #2

---

Coding/DataStructures/Introduction.md

updated data structure file #5

---

ProgrammingLanguages/C++/WhatIsSTL.md

I have added relevant article on the topic "What is STL". The articles includes from basics about STL in C++. The article also talks about the core components of STL  what are they used for and their types - Containers, Algorithms and  the Iterators with their specific types. Also, benefits of using STL are highlighted.
fix #44

Added Article on WhatIsSTL?

---

ProgrammingLanguages/JavaScript/WhatIsDOM.md
ProgrammingLanguages/JavaScript/WhatIsJS.md
Web/HowToLearnJS.md

This PR adds the following:
* `ProgrammingLanguages/JavaScript` directory 
* `WhatIsJS.md`
* WhatIsDOM.md`
* Updates `Web/HowToLearnJS.md` to link to the DOM documentation 
This addresses issue #62

Add `WhatIsDOM.md` and `WhatIsJS.md` to `ProgrammingLanguages/JavaScript` directory

---

ProgrammingLanguages/Python/HowToLearnPython.md

This PR addresses issue #60 and adds Python to the mix!

Add `HowToLearnPython.md` to `ProgrammingLanguages`

---

Web/WhatisBackendDevelopment.md

please kindly merge the pull request
closes #49

WhatisBackendDevelopment.md Added

---

ML/DeepLearning.md
ML/NLP.md
ML/SupervisedLearning.md
ML/UnsupervisedLearning.md
ML/WhatIsMl.md

content for ML

---

Coding/DataStructures/Introduction.md
General/DBMS.md

Updated basics of database management systems in DBMS.md present in general folder. This will close issue #35

Added DBMS.md in general folder

---

ML/AutoML.md

add ML content

---

AI/WhatIsAI.md

detailed version of whatisai.md #56

---

Web/WhatIsNodeJS.md

Added content for Web/WhatIsNodeJS.md
#53

Added content for Web/WhatIsNodeJS.md

---

ML/ComputerVision.md
ML/MLToolsAndFrameworks.md
ML/MLinCybersecurity.md
ML/MLinHealthCare.md
ML/TheFutureOfML.md

Added content for files present in the ML folder.
#54

Added content for files present in ML folder

---

General/SystemDesign.md

Added System Design file #70

---

Web/WhatIsNodeJS.md

I have updated the content of WhatIsNodeJS.md. Please Kindly merge the Pull request.
Thank You
fix #53

Updated WhatIsNodeJS.md

---

General/Discrete Mathematics.md

Create Discrete Mathematics.md

---

General/DiscreteMathematics.md

Created a Discrete Mathematics README and added content

Discrete Mathematics README created and content added

---

ML/ComputerVision.md

#76  Added the required information in ComputerVision.md which is very knowledgeable.

Updated ComputerVision.md

---

General/WhatIsLowLevelProgramming.md

What is low level language 
